version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    ports:
      - "5431:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    ports:
      - "8080:80"